{% set version = "2.5.0" %}

package:
  name: libtensor
  version: {{ version }}

source:
    path: ../

build:
  ignore_run_exports:
    - mkl

requirements:
  build:
    - {{ compiler('cxx') }}
    - mkl-devel {{ mkl }}
    - cmake >=3.2
    - ninja
    # - ccache

  host:
    - mkl-devel {{ mkl }}

  run:
    - {{ pin_compatible('mkl', upper_bound='2021.0') }}

files:
  - include/libtensor
  - include/libutil
  - lib/libtensor*
  - lib/libutil*
  - share/cmake/libtensor

test:
  requires:
      - mkl {{ mkl }}
  commands:
      - test -f $PREFIX/lib/libtensor$SHLIB_EXT
      - test -f $PREFIX/lib/libutil$SHLIB_EXT
      # - ldd -r -u $PREFIX/lib/libtensor$SHLIB_EXT              # [linux]
      - ldd -v $PREFIX/lib/libtensor$SHLIB_EXT                 # [linux]
      - otool -L $PREFIX/lib/libtensor$SHLIB_EXT               # [osx]
      - conda inspect linkages --show-files --groupby=dependency libtensor
      - conda inspect objects -p $PREFIX $PKG_NAME           # [osx]

about:
  home: https://github.com/epifanovsky/libtensor
  dev_url: https://github.com/adc-connect/libtensor
  license: BSL-1.0 License
  license_family: BSL
  license_file: {{ SRC_DIR }}/LICENSE
  summary: "C++ library for tensor computations"
